CREATE TABLE [dbo].[ESSearchSimple] (
    [id]             INT            IDENTITY (1, 1) NOT NULL,
    [URL]            VARCHAR (4000) NULL,
    [username]       INT            NULL,
    [mycomment]      VARCHAR (768)  NULL,
    [searchname]     VARCHAR (255)  NULL,
    [recorddate]     DATETIME       NULL,
    [isglobal]       INT            NULL,
    [reporttype]     INT            NULL,
    [profile]        VARCHAR (128)  NULL,
    [query_limit]    VARCHAR (16)   NULL,
    [time_limit]     VARCHAR (32)   NULL,
    [acknowledged]   VARCHAR (24)   NULL,
    [start_date]     DATETIME       NULL,
    [end_date]       DATETIME       NULL,
    [order_1]        VARCHAR (24)   NULL,
    [order_2]        VARCHAR (24)   NULL,
    [use_date]       INT            NULL,
    [order_1_desc]   INT            NULL,
    [order_2_desc]   INT            NULL,
    [DistinctValues] VARCHAR (128)  NULL,
    [GroupChart]     INT            NULL,
    [run_count]      INT            NULL,
    [hide_col]       VARCHAR (128)  NULL,
    [category]       VARCHAR (64)   NULL,
    [readonly]       INT            NULL,
    [page]           VARCHAR (96)   NULL,
    [review]         VARCHAR (50)   NULL,
    CONSTRAINT [PK_ESSearchSimple] PRIMARY KEY CLUSTERED ([id] ASC)
);

