CREATE TABLE [dbo].[ESStrings] (
    [id]                             INT            IDENTITY (1, 1) NOT NULL,
    [name]                           VARCHAR (1024) NULL,
    [ESApplication]                  INT            NULL,
    [ESService]                      INT            NULL,
    [ESDiskspace]                    INT            NULL,
    [ESMotionTracking]               INT            NULL,
    [ESNessusLog]                    INT            NULL,
    [ESFlatFile]                     INT            NULL,
    [ESFlatFileDelim]                INT            NULL,
    [ESTrackingAccountGroups]        INT            NULL,
    [ESTrackingAccountComputers]     INT            NULL,
    [ESTrackingAccountUsers]         INT            NULL,
    [ESTrackingPolicy]               INT            NULL,
    [ESTrackingPolicyPasswordPolicy] INT            NULL,
    [ESTrackingPolicyAuditPol]       INT            NULL,
    [ESTrackingPolicyAuditPolCat]    INT            NULL,
    [ESTrackingPolicyAuditPolSubcat] INT            NULL,
    [ESTrackingPolicyAuditPolChg]    INT            NULL,
    [ESTrackingPolicyKerberosPolicy] INT            NULL,
    [ESTrackingPolicyUsrLogonRightS] INT            NULL,
    [ESTrackingPolicyUsrLogonRightL] INT            NULL,
    [ESTrackingPolicyTrust]          INT            NULL,
    [ESTrackingPolicyTrustType]      INT            NULL,
    [ESTrackingPolicyTrustDirection] INT            NULL,
    [ESTrackingPolicyTrustSIDFilter] INT            NULL,
    [ESTrackingLogonAuthType]        INT            NULL,
    [ESTrackingLogonAuthProtocol]    INT            NULL,
    [ESTrackingLogonFailureReason]   INT            NULL,
    [ESTrackingLogonProcess]         INT            NULL,
    [ESTrackingLogonType]            INT            NULL,
    [ESUptimeHistory]                INT            NULL,
    CONSTRAINT [PK_ESStrings] PRIMARY KEY CLUSTERED ([id] ASC)
);

