CREATE TABLE [dbo].[ESSysinfo] (
    [recorddate]                DATETIME       NULL,
    [groupname]                 INT            NULL,
    [computer]                  INT            NULL,
    [OS]                        VARCHAR (128)  NULL,
    [SystemRoot]                INT            NULL,
    [Manufacturer]              VARCHAR (64)   NULL,
    [Model]                     VARCHAR (128)  NULL,
    [TotalMemory]               INT            NULL,
    [CPUCount]                  INT            NULL,
    [CPUSpeed]                  INT            NULL,
    [CPUDescription]            VARCHAR (64)   NULL,
    [RegisteredOwner]           VARCHAR (128)  NULL,
    [RegisteredCompany]         VARCHAR (128)  NULL,
    [BiosSerial]                VARCHAR (128)  NULL,
    [BiosVersion]               VARCHAR (48)   NULL,
    [DisplayColorDepth]         INT            NULL,
    [DisplayHorizontalRes]      INT            NULL,
    [DisplayVerticalRes]        INT            NULL,
    [DisplayAdapter]            VARCHAR (64)   NULL,
    [MemMaxDevices]             INT            NULL,
    [MemMaxCapacity]            INT            NULL,
    [MemErrorCorrection]        VARCHAR (32)   NULL,
    [CountFloppy]               INT            NULL,
    [CountCDROM]                INT            NULL,
    [CountDVD]                  INT            NULL,
    [CountRemovable]            INT            NULL,
    [Uptime]                    INT            NULL,
    [CPUCountPhysical]          INT            NULL,
    [CPUCountLogical]           INT            NULL,
    [CPUMultiCore]              INT            NULL,
    [CPUHyperThreading]         INT            NULL,
    [CPUFamily]                 INT            NULL,
    [CPUModel]                  INT            NULL,
    [CPUStepping]               INT            NULL,
    [OSEdition]                 VARCHAR (128)  NULL,
    [ProductType]               VARCHAR (3)    NULL,
    [IsTerminalServer]          INT            NULL,
    [IsServerCore]              INT            NULL,
    [IsHyperV]                  INT            NULL,
    [ServicePackNum]            INT            NULL,
    [Is64Bit]                   INT            NULL,
    [DisplayMonitorCount]       INT            NULL,
    [OSInstallDate]             DATETIME       NULL,
    [IsVM]                      INT            NULL,
    [VMDescription]             VARCHAR (64)   NULL,
    [UptimeMax]                 INT            NULL,
    [UptimeTimestamp]           DATETIME       NULL,
    [ESAgentVersion]            VARCHAR (16)   NULL,
    [CPUSupportsVirtualization] INT            NULL,
    [chassistype]               VARCHAR (64)   NULL,
    [uaclevel]                  INT            NULL,
    [hasdockingstation]         INT            NULL,
    [timeZoneUtcOffset]         INT            NULL,
    [timeZoneDescription]       VARCHAR (96)   NULL,
    [lastserverinventoryupdate] DATETIME       NULL,
    [isSnmp]                    INT            NULL,
    [snmpSysObjectId]           VARCHAR (2048) NULL,
    CONSTRAINT [FK_ESSysinfo_ESEventlogComputer] FOREIGN KEY ([computer]) REFERENCES [dbo].[ESEventlogComputer] ([id])
);


GO
CREATE UNIQUE CLUSTERED INDEX [IDX_ES_Sysinfo_Unique]
    ON [dbo].[ESSysinfo]([computer] ASC) WITH (FILLFACTOR = 80);

