CREATE TABLE [dbo].[ESTrackingPolicy] (
    [recorddate_unix]            INT          NULL,
    [recorddate]                 DATETIME     NULL,
    [computername]               INT          NULL,
    [ComputerProductType]        VARCHAR (3)  NULL,
    [eventnumber]                BIGINT       NULL,
    [eventid]                    INT          NULL,
    [policy_type]                INT          NULL,
    [operation_type]             INT          NULL,
    [CallerUser]                 INT          NULL,
    [CallerDomain]               INT          NULL,
    [CallerAccountID]            INT          NULL,
    [CallerAccountSID]           INT          NULL,
    [CallerLogonID]              VARCHAR (16) NULL,
    [SourceComputer]             INT          NULL,
    [SourceIP]                   INT          NULL,
    [UserLogonRightShort]        INT          NULL,
    [UserLogonRightLong]         INT          NULL,
    [TargetAccountID]            INT          NULL,
    [TargetAccountSID]           INT          NULL,
    [TargetDomain]               INT          NULL,
    [TargetDomainID]             INT          NULL,
    [TrustType]                  INT          NULL,
    [TrustDirection]             INT          NULL,
    [TrustAttributes]            INT          NULL,
    [TrustSIDFiltering]          INT          NULL,
    [apSystemS]                  INT          NULL,
    [apSystemF]                  INT          NULL,
    [apLogonLogoffS]             INT          NULL,
    [apLogonLogoffF]             INT          NULL,
    [apObjectAccessS]            INT          NULL,
    [apObjectAccessF]            INT          NULL,
    [apPrivilegeUseS]            INT          NULL,
    [apPrivilegeUseF]            INT          NULL,
    [apDetailedTrackingS]        INT          NULL,
    [apDetailedTrackingF]        INT          NULL,
    [apPolicyChangeS]            INT          NULL,
    [apPolicyChangeF]            INT          NULL,
    [apAccountManagementS]       INT          NULL,
    [apAccountManagementF]       INT          NULL,
    [apDirectoryServiceAccessS]  INT          NULL,
    [apDirectoryServiceAccessF]  INT          NULL,
    [apAccountLogonS]            INT          NULL,
    [apAccountLogonF]            INT          NULL,
    [apCategory]                 INT          NULL,
    [apSubcategory]              INT          NULL,
    [apSubcategoryGUID]          INT          NULL,
    [apChanges]                  INT          NULL,
    [kerbChanges]                INT          NULL,
    [dpMinPasswordAge]           INT          NULL,
    [dpMaxPasswordAge]           INT          NULL,
    [dpForceLogoff]              INT          NULL,
    [dpLockoutThreshold]         INT          NULL,
    [dpLockoutObservationWindow] INT          NULL,
    [dpLockoutDuration]          INT          NULL,
    [dpPasswordProperties]       INT          NULL,
    [dpMinPasswordLength]        INT          NULL,
    [dpMinPasswordHistoryLength] INT          NULL,
    [dpMachineAccountQuota]      INT          NULL,
    [dpMixedDomainMode]          INT          NULL,
    [dpDomainBehaviorVersion]    INT          NULL,
    [dpChangeType]               INT          NULL,
    CONSTRAINT [FK_ESTrackingPolicy_ESEventlogAccountDomain] FOREIGN KEY ([CallerDomain]) REFERENCES [dbo].[ESEventlogAccountDomain] ([id]),
    CONSTRAINT [FK_ESTrackingPolicy_ESEventlogAccountUser] FOREIGN KEY ([CallerUser]) REFERENCES [dbo].[ESEventlogAccountUser] ([id]),
    CONSTRAINT [FK_ESTrackingPolicy_ESEventlogComputer] FOREIGN KEY ([computername]) REFERENCES [dbo].[ESEventlogComputer] ([id]),
    CONSTRAINT [FK_ESTrackingPolicy_ESEventlogSID] FOREIGN KEY ([CallerAccountSID]) REFERENCES [dbo].[ESEventlogSID] ([id]),
    CONSTRAINT [FK_ESTrackingPolicy_ESEventlogUser] FOREIGN KEY ([CallerAccountID]) REFERENCES [dbo].[ESEventlogUser] ([id])
);


GO
CREATE CLUSTERED INDEX [IDX_ES_TrackingPolicy]
    ON [dbo].[ESTrackingPolicy]([recorddate] ASC) WITH (FILLFACTOR = 80);

