CREATE TABLE [dbo].[ESEventlogComputer] (
    [id]                            INT            IDENTITY (1, 1) NOT NULL,
    [eventcomputer]                 VARCHAR (255)  NULL,
    [ipaddress]                     VARCHAR (40)   NULL,
    [ipaddress_dns]                 VARCHAR (40)   NULL,
    [utcEnabledTimestamp]           BIGINT         NULL,
    [ESEventlogMain]                INT            NULL,
    [ESDiskspace]                   INT            NULL,
    [ESEnvironment]                 INT            NULL,
    [ESPSTracking]                  INT            NULL,
    [ESHeartbeat]                   INT            NULL,
    [ESPerformance]                 INT            NULL,
    [ESLogonTracking]               INT            NULL,
    [ESPrintTracking]               INT            NULL,
    [ESService]                     INT            NULL,
    [ESApplication]                 INT            NULL,
    [ESMotionTracking]              INT            NULL,
    [ESHeartbeatPingTracking]       INT            NULL,
    [ESNessusLog]                   INT            NULL,
    [ESEventlogMainImported]        INT            NULL,
    [ESFlatFile]                    INT            NULL,
    [ESFlatFileDelim]               INT            NULL,
    [ESFolderStatus]                INT            NULL,
    [ESFilemon]                     INT            NULL,
    [ESSyslog]                      INT            NULL,
    [ESSyslogHost]                  INT            NULL,
    [ESLogonTrackingClient]         INT            NULL,
    [ESSysinfo]                     INT            NULL,
    [ESObjectTracking]              INT            NULL,
    [ESObjectTrackingClient]        INT            NULL,
    [ESTrackingAccountGroups]       INT            NULL,
    [ESTrackingAccountComputers]    INT            NULL,
    [ESTrackingAccountComputersCli] INT            NULL,
    [ESTrackingAccountUsers]        INT            NULL,
    [ESTrackingAccountUsersClient]  INT            NULL,
    [ESTrackingPolicy]              INT            NULL,
    [ESTrackingAuthFailure]         INT            NULL,
    [ESTrackingAuthFailureClient]   INT            NULL,
    [ESTrackingLogonByType]         INT            NULL,
    [ESTrackingLogonByTypeClient]   INT            NULL,
    [ESTrackingLogonAuth]           INT            NULL,
    [ESUptimeHistory]               INT            NULL,
    [ESDiskspaceLargeFiles]         INT            NULL,
    [ComputerStatus]                INT            NULL,
    [ESActionTriggerHistory]        INT            NULL,
    [ESSnmpTrapSender]              INT            NULL,
    [ESSnmpTrapReceiver]            INT            NULL,
    [Notes]                         VARCHAR (2048) NULL,
    [ESArpReceiver]                 INT            NULL,
    [ESArpSender]                   INT            NULL,
    [ESScheduledTasks]              INT            NULL,
    [ESSysinfoVirtualMachines]      INT            NULL,
    [ESPackageAssignments]          INT            NULL,
    CONSTRAINT [PK_ESEventlogComputer] PRIMARY KEY CLUSTERED ([id] ASC)
);

